### ISSUE TITLE
Output from flatfile db sources?

### ISSUE THREAD

**Issue by jult** [eduh/Pivotx-To-Wordpress#1]
I have a broken pivotx install, that is to say, the db dir and its entries are fully in tact, but the rest of pivotx is not.
I assumed this would work for such a circumstance, since it works outside of pivotx.
I tried, but it redirected me to an open script file on github. Something's not going as it should..

**Comment by eduh** [comment]
Hi,
I'm not sure what you mean with the redirect. Can I replay it with a URL ?  FYI:  you 'could'  also run the script on a commandline in a shell environment

**Comment by eduh** [comment]
And...if the DB is intact you can also dump the DB and  reinstall pivotX and restore the db.....

**Comment by jult** [comment]
"Before executing you should setup your database connection at the beginning of the file." 
It's a flatfile db, as far as I know it does not have any credentials. What do I set it to in your exporter then? Your readme needs examples.

**Comment by eduh** [comment]
Hi,
Sorry to say that this exporter uses the scenario that PivotX is running with a MySQL backend. I will make a note of that in the readme.   I wrote this script for a one time job and it is unlikely I will do a version for flat files.  Perhaps it is best to post something on the PivotX forum. But if your pivotx is broken why noty backup your dbfiles and reinstall poivotx and then restore the dbfile ?

**Comment by jult** [comment]
I had already fixed up a working pivotx install, that's not the issue here.
Perhaps I can convert the flatfile to mysql first. I'll check that out.

**Comment by eduh** [comment]
Yep, that would be a good idea.

**Comment by hansfn** [comment]
Hi, I would try the PivotX WXRExport extension. Then you don't need to convert your installation to MySQL. 

[Download the latest hook_wxrexport.php](http://sourceforge.net/p/pivot-weblog/code/HEAD/tree/extensions/wxrexport/hook_wxrexport.php?format=raw) and put it pivotx/extensions/wxrexport/ The possible export options are available from the extension's configuration page. (Edit inside the file to change behaviour. Look for CHANGE in the file - or just read the file from the beginning.)

Also see relevant [PivotX forum thread](http://forum.pivotx.net/viewtopic.php?f=17&t=3578).

**Comment by jult** [comment]
To close this, I think it's best to link this, so others can find the migratory solution as well: http://forum.pivotx.net/viewtopic.php?f=17&t=3578&sid=a0738c676ceadee3d9c285ea18a9cc9a&start=40
